handler: transform.js
languages:
  - ace
  - acm # No WP
  - acq # No WP
  - ady
  - aeb # No WP
  - af
  - ajp # No WP
  - am
  - an
  - ang
  - apc # No WP
  - ar
  - ars # No WP
  - ary
  - arz
  - as
  - ast
  - av
  - awa
  - ay
  - az
  - azb
  - ba
  - ban
  - bar
  - be
  - bem # No WP
  - be-tarask
  - bg
  - bh
  - bho # This will get mapped to 'bh' while requesting to MinT server
  - bi
  - bjn
  - bm
  - bn
  - bo
  - bs
  - bug
  - ca
  - ce
  - ceb
  - ch
  - cjk # No WP
  - ckb
  - cr
  - crh
  - cs
  - cy
  - da
  - din
  - dyu # No WP
  - dz
  - ee
  - el
  - en
  - eo
  - es
  - et
  - eu
  - fa
  - ff
  - fi
  - fj
  - fo
  - fon # No WP
  - fr
  - frp
  - fur
  - ga
  - gag
  - gan # T343450
  - gd
  - gl
  - gn
  - gor
  - gu
  - gv
  - ha
  - he
  - hi
  - hif
  - hne # No WP
  - hr
  - ht
  - hu
  - hy
  - id
  - ig
  - ilo
  - is
  - it
  - iu
  - ja
  - jam
  - jv
  - ka
  - kab
  - kac # No WP
  - kam # No WP
  - kbd
  - kbp
  - kea # No WP
  - kg
  - ki
  - kk
  - km
  - kmb # No WP
  - kn
  - knc # No WP
  - ko
  - koi
  - kr
  - krc
  - ks
  - ku
  - kv
  - ky
  - lb
  - lg
  - li
  - lij
  - lmo
  - ln
  - lo
  - lt
  - ltg
  - lua # No WP
  - luo # No WP
  - lus # No WP
  - lv
  - mag # No WP
  - mai
  - mdf
  - mg
  - mi
  - min
  - mk
  - ml
  - mn
  - mni
  - mnw
  - mos # No WP
  - mr
  - ms
  - mt
  - my
  - myv
  - mwl
  - nan
  - nb # This will get mapped to 'no' while requesting to MinT server
  - nds
  - nds-nl
  - ne
  - new
  - nl
  - nn
  - no
  - nso
  - nus # No WP
  - ny
  - oc
  - om
  - or
  - os
  - pa
  - pag
  - pam
  - pap
  - pl
  - ps
  - pt
  - qu
  - rn
  - ro
  - ru
  - rw
  - sa
  - sc
  - scn
  - sd
  - sg
  - sh
  - shn
  - si
  - simple # This will get mapped to 'en' while requesting to MinT server
  - sk
  - skr
  - sl
  - sm
  - sn
  - so
  - sq
  - sr
  - srn
  - ss
  - st
  - su
  - sv
  - sw
  - szl
  - ta
  - taq # No WP
  - tcy
  - te
  - tet
  - tg
  - th
  - ti
  - tk
  - tl
  - tn
  - tpi
  - tr
  - ts
  - tt
  - tum
  - tw
  - tyv
  - tzm # No WP
  - ug
  - uk
  - umb # No WP
  - ur
  - uz
  - ve
  - vec
  - vi
  - war
  - wo
  - wuu
  - xal
  - xh
  - yi
  - yo
  - zh
  - zu
# Specific language pairs
pairs:
  en:
    - bcl # en->bcl is provided by OpusMT and it is single direction
    - bi # OpusMT single direction pair.
    - br
    - brx # IndicTrans2 only provides en<->brx, No wiki yet.
    - chr # OpusMT single direction pair.
    - doi # IndicTrans2 only provides en<->doi, No wiki yet.
    - gom # IndicTrans2 only provides en<->gom
    - guw # OpusMT single direction pair.
    - sat # IndicTrans2 only provides en<->santali
    - srn # OpusMT single direction pair.
    - to # OpusMT single direction pair.
    - ty # OpusMT single direction pair.
    - ve # OpusMT single direction pair.
    - zgh # Mapped with tzm in MinT (T364122).
  fr:
    - br
  brx:
    - en
    - simple
  doi:
    - en
    - simple
  gom:
    - en
    - simple
  sat:
    - en
    - simple
  simple:
    - bcl
    - brx
    - doi
    - gom
    - sat
  sv:
    - fi
